spring:
  application:
    name: projetofinal

  datasource:
    url: jdbc:mysql://localhost:3306/projeto
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: never
