spring:
  application:
    name: projetofinal

  datasource:
    url: jdbc:mysql://sql10.freesqldatabase.com:3306/sql10761415
    driverClassName: com.mysql.cj.jdbc.Driver
    username: sql10761415
    password: KlLzkGRWHR

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: never
